spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 5
      ack-mode: manual_immediate
    consumer:
      groupId: consumer-main
      topic: authors-topic
      enable-auto-commit: true
      auto-commit-interval-ms: 1000
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.ssscl.kafka.common.serializer.AuthorKafkaDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'com.ssscl.kafka.common'